### PR TITLE
🔍: Upgrade Axios to 1.6.2 to fix the sui-domain and sui-mockmock vulnerabilities

### PR DESCRIPTION
**Pull request by nucliweb**
## Description

Upgrade Axios to 1.6.2 to fix the [sui-domain](https://github.com/SUI-Components/sui/security/dependabot/37) and [sui-mockmock](https://github.com/SUI-Components/sui/security/dependabot/38) vulnerabilities

### CODE REVIEW

**Review by kikoruiz — APPROVED** [review]

**Review by jordevo — APPROVED** [review]

**Comment by jordevo** [comment]
did you have a look at potential issues with the upgrade? there's nothing official AFAIK but here's some crowd-sourced documentation / guide: https://github.com/bmuenzenmeyer/axios-1.0.0-migration-guide

**Comment by nucliweb** [comment]
> did you have a look at potential issues with the upgrade? there's nothing official AFAIK but here's some crowd-sourced documentation / guide: https://github.com/bmuenzenmeyer/axios-1.0.0-migration-guide

Thanks @jordevo, we don't use the `@bundled-es-modules/axios` package

**Comment by jordevo** [comment]
> > did you have a look at potential issues with the upgrade? there's nothing official AFAIK but here's some crowd-sourced documentation / guide: https://github.com/bmuenzenmeyer/axios-1.0.0-migration-guide
> 
> Thanks @jordevo, we don't use the `@bundled-es-modules/axios` package

not sure I'm following... the non-official migration guide refers to the `axios` package

**Comment by nucliweb** [comment]
> > > did you have a look at potential issues with the upgrade? there's nothing official AFAIK but here's some crowd-sourced documentation / guide: https://github.com/bmuenzenmeyer/axios-1.0.0-migration-guide
> > 
> > 
> > Thanks @jordevo, we don't use the `@bundled-es-modules/axios` package
> 
> not sure I'm following... the non-official migration guide refers to the `axios` package

We import Axios from Axios, not from `@bundled-es-modules/axios`

image


https://github.com/SUI-Components/sui/blob/feat%2Fupgrade-domain-to-axios-1.6.2/packages/sui-domain/src/fetcher/AxiosFetcher.js#L1

**Review by andresz1 — APPROVED** [review]

**Pull request merged**
