### PR TITLE
feat(packages/sui-studio): Delete excess code for ux tab

### PR DESCRIPTION
**Pull request by corners2wall**
## Description

Delete excess code for ux tab
Closes [2376](https://github.com/SUI-Components/sui-components/issues/2376)

## Related Issue

According [#2376](https://github.com/SUI-Components/sui-components/issues/2376)

### CODE REVIEW

**Comment by arnau-rius** [comment]
I have approved workflow run from public fork 👍🏽

**Review by jordevo — APPROVED** [review]

**Review by arnau-rius — APPROVED** [review]

**Review by arnau-rius — APPROVED** [review]
@turolopezsanabria take a look on this please.
LGTM by the way @corners2wall 👏🏽

**Review by turolopezsanabria — APPROVED** [review]
👏🏼 thnks!

**Review by rmoralp — APPROVED** [review]

**Review by andresin87 — APPROVED** [review]

**Comment by rmoralp** [comment]
@corners2wall could you use `npm run co` to make a `feat` commit under `packages/sui-studio` scope in order to trigger a minor release?

**Comment by corners2wall** [comment]
@rmoralp, done

**Pull request merged**
