### PR TITLE
Feature/sui mono single package release

### PR DESCRIPTION
**Pull request by jcger**
#152

### CODE REVIEW

**Comment by davidbarna** [comment]
Good job. FYI I've been thinking a way to apply the package filter to any of sui-mono commands with a common option like so:

```sh
sui-mono release --pkg="category/*"
sui-mono commit-all -t=fix -m="A commit" --pkg="category/package"
sui-mono phoenix --pkg="category/*"
```

I'm just saying in case you wanna make your change more prepared for a common option for all commands.

Plus *the concept of category and component is a sui-studio concept, not sui-mono*.

**Comment by jcger** [comment]
I wasn't aware that there is an option called "deepLevel". Maybe this PR is useless as it doesn't includes deepLevel > 2, or maybe sui-mono does to much and should not allow deepLevel > 2

**Comment by davidbarna** [comment]
@jcger you may have to consider to close it or refactor 😢

**Comment by jcger** [comment]
I'll handle it as one and call it scope, so it would be possible to release a/very/long/but/single/deep/level/scope

**Pull request merged**
