### PR TITLE
fix(sui-react-initial-props): fix unnecesary unmount of pages

### PR DESCRIPTION
**Pull request by miduga**
## Description
It seems we're unmounting and mounting without need some pages. This is a first approach in order to address the problem. We need further testing in order to check this is not breaking anything, if this change let us to a major and how this change impact actual pages.

## Related Issue
https://github.com/SUI-Components/sui/issues/299

## Example
More info in the issue.

### CODE REVIEW

**Comment by carlesnunez** [comment]
Going to test it on real test environment

**Comment by davidbarna** [comment]
Build is failing but it might have nothing to do with your code. Just merge once your done even if the check fails.

**Comment by carlesnunez** [comment]
Seems that keep's not working. The current behavior with the fix is:

-> First render (from server) `componentDidMount`
-> Second render (from frontend, after a redirection) `componentDidMount` (BAD BEHAVIOR)
-> Next renders `componentDidUpdate` (GOOD BEHAVIOR from here)

As I told to @miduga this is happening because the first render is rendering a component with a different ref than the second render. This is happening due to we only fixed the case from client, not from the SSR.

**Comment by carlesnunez** [comment]
Whats the state of this pr?

**Comment by miduga** [comment]
Let's get tomorrow a momento in order to sit together and try new approaches @carlesnunez . :)

**Comment by carlesnunez** [comment]
Now that we've returned form holidays we can catchup with that when you want :)

**Comment by miduga** [comment]
We have discussed this some times in order to get in our JIRA board but always there is some other more important task to do. If this is causing a real problem on any implementation, then we definitely should focus on it, talk with our product owner and prioritize it accordingly. I understand that conceptually speaking is not correct but right now this is being used as a feature on all the products for getting the initial props for the component and perform some tracking and stuff in componentDidMount. We will arrange a meeting in order to understand better if this is causing a major problem in your project and thus prioritize it if needed or closing the ticket for now.

**Comment by carlesnunez** [comment]
Thank you for considering this in order to decide if is a problem or not! 👍

**Pull request closed without merging**
