### PR TITLE
Fix for Issue 1418: [@s-ui/pde] use structured args in useFeature

### LINKED ISSUE #1418: Request: use structured args in useFeature
### Package

pde@2

after https://github.com/SUI-Components/sui/pull/1410 

### Description

The hooks signature for `useExperiment` and `useFeature` is not coherent as:

- `useExperiment({experimentName, ...})` has structured args so you can pass to it the args you want in each field, p.ex.
```
useExperiment({experimentName: 'myExperiment'})
useExperiment({experimentName: 'myExperiment', adapterId: 'myAdapter'})
```

- `useFeature(...)` has raw args so you need to pass all args to fill the last one
```
useFeature('myFeature', null, null, 'myAdapter')
```

It would be nice to have both hooks signatures with structured args.

### PR DESCRIPTION
**Pull request by theonly1me**
Fix for Issue 1418: [@s-ui/pde] use structured args in useFeature

## Description

- Update `useFeature` hook to accept structured args instead of raw args
- Update unit tests to account for the changes to the `useFeature` hook
- Update README.md to account for changes to the `useFeature` hook
- Correct a spelling mistake in CONTRIBUTING.md (`versionning` -> `versioning`)

## Related Issue
Fix #1418 

### Example - 1
```javascript
const MyComponent = () => {
  const {isActive} = useFeature({featureKey: 'myFeatureKey'}) // isActive = true when the feature flag is activated

  return <p>The feature 'myFeatureKey' is {isActive ? 'active' : 'inactive'}</p>
}
```

### Example - 2
```javascript
 useFeature({
              featureKey: 'featureKey3',
              queryString: '?suipde_featureKey3=off&suipde_feature1=on'
            })
```

### CODE REVIEW

**Comment by theonly1me** [comment]
@rmoralp Can you please review this PR?

**Comment by arnau-rius** [comment]
I have approved workflow run from public fork 👍🏽

**Comment by arnau-rius** [comment]
Looks like something was wrong during the build. Let's see if we can take a closer look of the issue in the next days.

**Comment by theonly1me** [comment]
Thanks @arnau-rius, the following mocha test is failing:

```  
1) copyfiles
       should copy files from src to dest and flatten it:
     Error: ENOENT: no such file or directory, copyfile 'fixturesCopy/a.js' -> 'runtime/a.js'
```

It is trying to copy the `a.js` from `fixturesCopy` directory to the `runtime` directory. This runtime directory seems to be getting generated during the build. It could be a random failure from looking at the logs and since I don't really have any changes here. Could you please re-trigger the build?

**Comment by rmoralp** [comment]
BTW code looks great.

**Comment by theonly1me** [comment]
@rmoralp I have updated the commit type to `fix`. Could you please re-trigger the workflow build?

**Comment by rmoralp** [comment]
As I see, that commit names does not satisfy our conventional commit convention. You should  use `npm run co` to make the commits

**Comment by theonly1me** [comment]
@rmoralp, I see. I'll keep that in mind for any future PRs. Thanks

**Comment by andresin87** [comment]
@rmoralp this is a major. The version number must be (manual) updated also b4 merging if no commit message has it declared

**Comment by theonly1me** [comment]
@andresin87 do you want me to run the `npm version major` to bump the major version up?

**Comment by theonly1me** [comment]
@rmoralp @andresin87 I've bumped up the major version. I've also used the `npm run co` to create the commit this time around.

**Comment by theonly1me** [comment]
@rmoralp @andresin87 I've rebased my branch and fixed up the commits via the `npm run co`. The major version has been updated now. Please re-trigger the build workflow and feel free to let me know in case there's anything else you need me to do. Thanks.

**Comment by alextremp** [comment]
Hi @theonly1me which is the current status of this PR?
In a short period of time we'll had to add a new feature adding a new parameter to the useFeature ( #1601 ) and would be nice to have the structured args already

**Pull request closed without merging**
