### PR TITLE
feat(sui-i18n): add percentage formatting capability to i18n

### PR DESCRIPTION
**Pull request by jordevo**
Currently on our `i18n` we don't provide with a method to format percentages. 

## Description
This `PR` adds a new method `.p()` that adds a percentage sign to the number we pass on as a value.

## Example
`console.log(i18n.p(69));`

would tipically output:
`69 %`

### CODE REVIEW

**Comment by rmoralp** [comment]
Could you add some test? 
https://github.com/SUI-Components/sui/blob/master/packages/sui-i18n/test/i18nSpec.js

**Comment by jordevo** [comment]
hi @desko27 ! 

yes I thought of doing that instead but since percentages are part numbers and hence they're also localisable, I thought it'd be useful to have a similar approach to that of `.c` and `.n` ...

I didn't see any trade-off on that approach, is there any in any way?

**Comment by desko27** [comment]
@jordevo sorry I didn't explain properly.

The point I meant is the existing API: why `p` should be used for `percent` and not for `phone` which already exists in `f`?

Apart from that, simplicity of `p` can't be denied. Both solutions are ok for me, if no one has more thoughts to share 😄

**Comment by midudev** [comment]
Tbh, the `p` seems to be, at least, misleading. We're not forced to use a single char for methods on i18n. I would recommend to use as well the `f` function.

Maybe we could start exporting then properly named methods for the rest, like:

i18n.formatPercentatge() -> internally calls the `f` function.

**Pull request merged**
